### ISSUE TITLE
de4dot lacking x64 version cannot be added

### ISSUE THREAD

**Issue by sora324** [T5ive/Smart-de4dot#1]
Some versions of de4dot lack de4dot-x64.exe.In that case,it cannot be added into the directory.I suggest allowing adding the directory instead and pop up a window when trying to press x64 button.Thanks.

**Comment by T5ive** [comment]
updated https://github.com/T5ive/Smart-de4dot/commit/f0db20b93f6474c05e394596b81b5cda584c60b4

**Comment by sora324** [comment]
Thanks for your reply.Here's another bug:if I switch de4dot from a version with x64 to another without x64,the path doesn't change simultaneously.
And also I suggest removing the x64 error message completely by deleting FrmMain.cs - line 111.
Thank you.

**Comment by T5ive** [comment]
Oops, sorry, there shouldn't be anything wrong this time

**Comment by sora324** [comment]
Works perfectly.Thanks!
