### ISSUE TITLE
Tools Injector Mod Menu Error

### ISSUE THREAD

**Issue by PREETCHAUHAN** [T5ive/Smart-de4dot#2]
➡️ Sorry. I am Asking About https://github.com/T5ive/Tools-Injector-Mod-Menu Here !!

⬇️ Settings File ⤵️

[settings.json](https://github.com/user-attachments/files/16574265/settings.json)

⬇️ Log Here ⤵️

[2024-8-11 21-15-39.txt](https://github.com/user-attachments/files/16574227/2024-8-11.21-15-39.txt)

➡️ See the logs i am facing error i put the folder in c drive but nothing works, please help me out.

➡️ I can't make issues there, because that repo is archived.

⬇️ See Image Here ⤵️

![4](https://github.com/user-attachments/assets/e6961ab5-b9a7-4faa-8645-2853f06e5d59)

**Comment by T5ive** [comment]
Thanks for reporting the issue.
I have archived developing this project for a long time. 
If you have programming skills, you can fix it as follows:
1. Go to the PageCompile.cs file https://github.com/T5ive/Tools-Injector-Mod-Menu/blob/master/Tools%20Injector%20Mod%20Menu/Form/Pages/PageCompile.cs
2. Go to line 476 https://github.com/T5ive/Tools-Injector-Mod-Menu/blob/708c80c3125a3c80911674a8d6755a566f4c44ba/Tools%20Injector%20Mod%20Menu/Form/Pages/PageCompile.cs#L476 and change it from 
`if (!MoveDirectory(TEMP_PATH_T_FIVE + "\\com", $"{destinationPath}\\smali\\com", true, true))`
to `if (!MoveDirectory(TEMP_PATH_T_FIVE + "\\com", $"{destinationPath}smali\\com", true, true))`
This should solve your problem.

Sorry for not being able to update.
If you have any further questions, you can reply in this repository https://github.com/T5ive/T5ive

Thanks.

**Comment by PREETCHAUHAN** [comment]
But How Can I Implement I Am Using PC App Where I should Edit ?

i don't have enough space to install android studio on pc can you update the app ?

**Comment by constantbsn** [comment]
Hi, I did the change by forking your project : https://github.com/constantbsn/Tools-Injector-Mod-Menu-Error-Fixed . 
I don't know how to compile your project, could you please explain it ? Thanks
